/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OsRouteImport } from './routes/os'
import { Route as OsIndexRouteImport } from './routes/os.index'
import { Route as OsTasksRouteImport } from './routes/os.tasks'
import { Route as OsVmsRouteImport } from './routes/os.vms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIndexRoute = OsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OsRoute,
} as any)
const OsTasksRoute = OsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => OsRoute,
} as any)
const OsVmsRoute = OsVmsRouteImport.update({
  id: '/vms',
  path: '/vms',
  getParentRoute: () => OsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/os': typeof OsRouteWithChildren
  '/os/tasks': typeof OsTasksRoute
  '/os/vms': typeof OsVmsRoute
  '/os/': typeof OsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/os/tasks': typeof OsTasksRoute
  '/os/vms': typeof OsVmsRoute
  '/os': typeof OsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/os': typeof OsRouteWithChildren
  '/os/tasks': typeof OsTasksRoute
  '/os/vms': typeof OsVmsRoute
  '/os/': typeof OsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/os' | '/os/tasks' | '/os/vms' | '/os/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/os/tasks' | '/os/vms' | '/os'
  id: '__root__' | '/' | '/os' | '/os/tasks' | '/os/vms' | '/os/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OsRoute: typeof OsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/': {
      id: '/os/'
      path: '/'
      fullPath: '/os/'
      preLoaderRoute: typeof OsIndexRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/tasks': {
      id: '/os/tasks'
      path: '/tasks'
      fullPath: '/os/tasks'
      preLoaderRoute: typeof OsTasksRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/vms': {
      id: '/os/vms'
      path: '/vms'
      fullPath: '/os/vms'
      preLoaderRoute: typeof OsVmsRouteImport
      parentRoute: typeof OsRoute
    }
  }
}

interface OsRouteChildren {
  OsTasksRoute: typeof OsTasksRoute
  OsVmsRoute: typeof OsVmsRoute
  OsIndexRoute: typeof OsIndexRoute
}

const OsRouteChildren: OsRouteChildren = {
  OsTasksRoute: OsTasksRoute,
  OsVmsRoute: OsVmsRoute,
  OsIndexRoute: OsIndexRoute,
}

const OsRouteWithChildren = OsRoute._addFileChildren(OsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OsRoute: OsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
